# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Seristack < Formula
  desc "Seristack is a lightweight automation engine designed to bridge the gap between local task execution and remote triggers. Define your stacks in YAML, manage dependencies, and expose your automation via a built-in HTTP server."
  homepage "https://github.com/TechXploreLabs/seristack"
  version "0.0.1"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/TechXploreLabs/seristack/releases/download/v0.0.1/seristack_0.0.1_darwin_amd64.tar.gz"
      sha256 "34393f5c0df439c47ae1ea49fd922df65cbb490c83093fdbadb71e1786a890d1"

      def install
        bin.install "seristack"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/TechXploreLabs/seristack/releases/download/v0.0.1/seristack_0.0.1_darwin_arm64.tar.gz"
      sha256 "d9cce066e51c8ca90ed588cc5435948b034150db87d3623e79e87178b8d35317"

      def install
        bin.install "seristack"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/TechXploreLabs/seristack/releases/download/v0.0.1/seristack_0.0.1_linux_amd64.tar.gz"
      sha256 "d344a136c0c7e8e06b6afa294eafc0353535ae2f48198409467b18f0450ac2d4"
      def install
        bin.install "seristack"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/TechXploreLabs/seristack/releases/download/v0.0.1/seristack_0.0.1_linux_arm64.tar.gz"
      sha256 "34a2b83f82167e9a0e9b21f3bd2a6bcbbd01e1231abaf64ff54c3e47824b6cfc"
      def install
        bin.install "seristack"
      end
    end
  end
end
